kind: source
version: 1
id: plays
dataset: crm_db
table: plays
subject:
  - play_id
ts: created_at
dimensions:
  - name: play_id
    expr: play_id
    data_type: STRING
    is_primary_key: true
  - name: run_id
    expr: run_id
    data_type: STRING
  - name: workflow_id
    expr: workflow_id
    data_type: STRING
  - name: play_name
    expr: play_name
    data_type: STRING
  - name: created_at
    expr: created_at
    data_type: TIMESTAMP
measures:
  - name: play_count
    expr: "1"
    agg: COUNT
    data_type: INT64
