kind: source
version: 1
id: users
dataset: product_usage_db
table: dim_users
subject:
  - user_id
  - org_id
dimensions:
  - name: user_id
    expr: user_id
    data_type: STRING
    is_primary_key: true
  - name: org_id
    expr: org_id
    data_type: STRING
  - name: user_name
    expr: user_name
    data_type: STRING
  - name: is_active_user
    expr: is_active_user
    data_type: BOOL
  - name: is_new_user
    expr: is_new_user
    data_type: BOOL
  - name: is_returning_user
    expr: is_returning_user
    data_type: BOOL
  - name: is_churned_user
    expr: is_churned_user
    data_type: BOOL
measures:
  - name: user_count
    expr: "1"
    agg: COUNT
    data_type: INT64
  - name: active_user_count
    expr: CASE WHEN is_active_user THEN 1 ELSE 0 END
    agg: SUM
    data_type: INT64
  - name: new_user_count
    expr: CASE WHEN is_new_user THEN 1 ELSE 0 END
    agg: SUM
    data_type: INT64
  - name: returning_user_count
    expr: CASE WHEN is_returning_user THEN 1 ELSE 0 END
    agg: SUM
    data_type: INT64
  - name: churned_user_count
    expr: CASE WHEN is_churned_user THEN 1 ELSE 0 END
    agg: SUM
    data_type: INT64
joins:
  - to_source: orgs
    join_type: INNER
    left_key: org_id
    right_key: org_id
    relationship: many_to_one
